on:
  push:
    paths:
      - 'Data/Polls.csv'  
      - '.github/**'        
    branches:
      - main
      - master
  pull_request:
    paths:
      - 'Data/Polls.csv'
      - '.github/**'         
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: r-${{ hashFiles('DESCRIPTION') }} 
      - name: Install dependencies
        run: |
          Sys.getenv("GITHUB_REF")
          install.packages(c("remotes", "rcmdcheck", "httr"))
          remotes::install_deps(pkgdir = "RPackage", dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(path = "RPackage", args = "--no-manual", error_on = "error")          
        shell: Rscript {0}
